# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metadata/v1/constants.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'metadata/v1/constants.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bmetadata/v1/constants.proto\x12\x0bmetadata.v1\x1a google/protobuf/descriptor.proto:l\n#metadata_conduit_source_plugin_name\x12\x1c.google.protobuf.FileOptions\x18\xa0\x9c\x01 \x01(\tR\x1fmetadataConduitSourcePluginName:r\n&metadata_conduit_source_plugin_version\x12\x1c.google.protobuf.FileOptions\x18\xa1\x9c\x01 \x01(\tR\"metadataConduitSourcePluginVersion:v\n(metadata_conduit_destination_plugin_name\x12\x1c.google.protobuf.FileOptions\x18\xa2\x9c\x01 \x01(\tR$metadataConduitDestinationPluginName:|\n+metadata_conduit_destination_plugin_version\x12\x1c.google.protobuf.FileOptions\x18\xa3\x9c\x01 \x01(\tR\'metadataConduitDestinationPluginVersion:n\n$metadata_conduit_source_connector_id\x12\x1c.google.protobuf.FileOptions\x18\xa4\x9c\x01 \x01(\tR metadataConduitSourceConnectorId:d\n\x1fmetadata_conduit_dlq_nack_error\x12\x1c.google.protobuf.FileOptions\x18\xa5\x9c\x01 \x01(\tR\x1bmetadataConduitDlqNackError:g\n!metadata_conduit_dlq_nack_node_id\x12\x1c.google.protobuf.FileOptions\x18\xa6\x9c\x01 \x01(\tR\x1cmetadataConduitDlqNackNodeIdB\x95\x02Z6github.com/conduitio/conduit-commons/proto/metadata/v1\x82\xe2\t\x1a\x63onduit.source.plugin.name\x8a\xe2\t\x1d\x63onduit.source.plugin.version\x92\xe2\t\x1f\x63onduit.destination.plugin.name\x9a\xe2\t\"conduit.destination.plugin.version\xa2\xe2\t\x1b\x63onduit.source.connector.id\xaa\xe2\t\x16\x63onduit.dlq.nack.error\xb2\xe2\t\x18\x63onduit.dlq.nack.node.idb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metadata.v1.constants_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/conduitio/conduit-commons/proto/metadata/v1\202\342\t\032conduit.source.plugin.name\212\342\t\035conduit.source.plugin.version\222\342\t\037conduit.destination.plugin.name\232\342\t\"conduit.destination.plugin.version\242\342\t\033conduit.source.connector.id\252\342\t\026conduit.dlq.nack.error\262\342\t\030conduit.dlq.nack.node.id'
# @@protoc_insertion_point(module_scope)
