# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: config/v1/parameter.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'config/v1/parameter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63onfig/v1/parameter.proto\x12\tconfig.v1\"\xad\x02\n\tParameter\x12\x18\n\x07\x64\x65\x66\x61ult\x18\x01 \x01(\tR\x07\x64\x65\x66\x61ult\x12 \n\x0b\x64\x65scription\x18\x02 \x01(\tR\x0b\x64\x65scription\x12-\n\x04type\x18\x03 \x01(\x0e\x32\x19.config.v1.Parameter.TypeR\x04type\x12\x37\n\x0bvalidations\x18\x04 \x03(\x0b\x32\x15.config.v1.ValidationR\x0bvalidations\"|\n\x04Type\x12\x14\n\x10TYPE_UNSPECIFIED\x10\x00\x12\x0f\n\x0bTYPE_STRING\x10\x01\x12\x0c\n\x08TYPE_INT\x10\x02\x12\x0e\n\nTYPE_FLOAT\x10\x03\x12\r\n\tTYPE_BOOL\x10\x04\x12\r\n\tTYPE_FILE\x10\x05\x12\x11\n\rTYPE_DURATION\x10\x06\"\xe7\x01\n\nValidation\x12.\n\x04type\x18\x01 \x01(\x0e\x32\x1a.config.v1.Validation.TypeR\x04type\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value\"\x92\x01\n\x04Type\x12\x14\n\x10TYPE_UNSPECIFIED\x10\x00\x12\x11\n\rTYPE_REQUIRED\x10\x01\x12\x15\n\x11TYPE_GREATER_THAN\x10\x02\x12\x12\n\x0eTYPE_LESS_THAN\x10\x03\x12\x12\n\x0eTYPE_INCLUSION\x10\x04\x12\x12\n\x0eTYPE_EXCLUSION\x10\x05\x12\x0e\n\nTYPE_REGEX\x10\x06\x42\x36Z4github.com/conduitio/conduit-commons/proto/config/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'config.v1.parameter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z4github.com/conduitio/conduit-commons/proto/config/v1'
  _globals['_PARAMETER']._serialized_start=41
  _globals['_PARAMETER']._serialized_end=342
  _globals['_PARAMETER_TYPE']._serialized_start=218
  _globals['_PARAMETER_TYPE']._serialized_end=342
  _globals['_VALIDATION']._serialized_start=345
  _globals['_VALIDATION']._serialized_end=576
  _globals['_VALIDATION_TYPE']._serialized_start=430
  _globals['_VALIDATION_TYPE']._serialized_end=576
# @@protoc_insertion_point(module_scope)
