# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: procutils/v1/schema.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'procutils/v1/schema.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from schema.v1 import schema_pb2 as schema_dot_v1_dot_schema__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19procutils/v1/schema.proto\x12\x0cprocutils.v1\x1a\x16schema/v1/schema.proto\"q\n\x13\x43reateSchemaRequest\x12\x18\n\x07subject\x18\x01 \x01(\tR\x07subject\x12*\n\x04type\x18\x02 \x01(\x0e\x32\x16.schema.v1.Schema.TypeR\x04type\x12\x14\n\x05\x62ytes\x18\x03 \x01(\x0cR\x05\x62ytes\"A\n\x14\x43reateSchemaResponse\x12)\n\x06schema\x18\x01 \x01(\x0b\x32\x11.schema.v1.SchemaR\x06schema\"F\n\x10GetSchemaRequest\x12\x18\n\x07subject\x18\x01 \x01(\tR\x07subject\x12\x18\n\x07version\x18\x02 \x01(\x05R\x07version\">\n\x11GetSchemaResponse\x12)\n\x06schema\x18\x01 \x01(\x0b\x32\x11.schema.v1.SchemaR\x06schemaB?Z=github.com/conduitio/conduit-processor-sdk/proto/procutils/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'procutils.v1.schema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=github.com/conduitio/conduit-processor-sdk/proto/procutils/v1'
  _globals['_CREATESCHEMAREQUEST']._serialized_start=67
  _globals['_CREATESCHEMAREQUEST']._serialized_end=180
  _globals['_CREATESCHEMARESPONSE']._serialized_start=182
  _globals['_CREATESCHEMARESPONSE']._serialized_end=247
  _globals['_GETSCHEMAREQUEST']._serialized_start=249
  _globals['_GETSCHEMAREQUEST']._serialized_end=319
  _globals['_GETSCHEMARESPONSE']._serialized_start=321
  _globals['_GETSCHEMARESPONSE']._serialized_end=383
# @@protoc_insertion_point(module_scope)
