# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema/v1/schema.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'schema/v1/schema.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16schema/v1/schema.proto\x12\tschema.v1\"\xbb\x01\n\x06Schema\x12\x18\n\x07subject\x18\x01 \x01(\tR\x07subject\x12\x18\n\x07version\x18\x02 \x01(\x05R\x07version\x12\x0e\n\x02id\x18\x03 \x01(\x05R\x02id\x12*\n\x04type\x18\x04 \x01(\x0e\x32\x16.schema.v1.Schema.TypeR\x04type\x12\x14\n\x05\x62ytes\x18\x05 \x01(\x0cR\x05\x62ytes\"+\n\x04Type\x12\x14\n\x10TYPE_UNSPECIFIED\x10\x00\x12\r\n\tTYPE_AVRO\x10\x01\x42\x36Z4github.com/conduitio/conduit-commons/proto/schema/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema.v1.schema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z4github.com/conduitio/conduit-commons/proto/schema/v1'
  _globals['_SCHEMA']._serialized_start=38
  _globals['_SCHEMA']._serialized_end=225
  _globals['_SCHEMA_TYPE']._serialized_start=182
  _globals['_SCHEMA_TYPE']._serialized_end=225
# @@protoc_insertion_point(module_scope)
